# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Down to the Wire
#tagline:             'Elements of LabVIEW'
description:         'A blog by <a href="https://twitter.com/JoeFriedrichsen" target="_blank">@JoeFriedrichsen</a>.'
url:                 http://downtothewire.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Joe Friedrichsen
  url:               https://twitter.com/JoeFriedrichsen
  email:             all.wired.down@gmail.com

