#Permalinks
permalink:           pretty

# Setup
title:               ML@B
tagline:             'Blog'
description:         'The official blog of <a href="http://ml.berkeley.edu">Machine Learning @ Berkeley</a>.'
url:                 http://ml.berkeley.edu
baseurl:             /blog
paginate:            5
paginate_path:       "page:num"

# About/contact
author:
  name:              ML@B
  url:               https://ml.berkeley.edu/
  email:             ml.at.berkeley@gmail.com
  facebook:          berkeleyml
  twitter:           berkeleyml
  github:            mlberkeley
  linkedin:          machine-learning-at-berkeley

# Custom vars
version:             1.0.0
future:             true 

excerpt_separator:   <!-- break -->

gems: [jekyll-paginate]

